### PR TITLE
Update Gems

### PR DESCRIPTION
**Pull request by nixpulvis**
GitHub is complaining about security issues in the current versions of our gems. Updating should fix.

### CODE REVIEW

**Comment by nixpulvis** [comment]
@octopushugs https://github.com/ForwardFinancing/forwardfinancing.github.io/network/alerts

**Comment by octopushugs** [comment]
> @octopushugs https://github.com/ForwardFinancing/forwardfinancing.github.io/network/alerts

Looks like that's 404ing

**Comment by nixpulvis** [comment]
Not for me... weird. Do you get a notice in yellow about this issue here? https://github.com/ForwardFinancing/forwardfinancing.github.io

**Comment by octopushugs** [comment]
> Not for me... weird. Do you get a notice in yellow about this issue here? https://github.com/ForwardFinancing/forwardfinancing.github.io

I do now! For closure: I was not an admin user on the repo, so was unable to see said alert. Bumping permission solved that.

**Pull request merged**
